site_name: Painel de Planejamento e Orçamento de Minas Gerais
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    scheme: default
    primary: blue grey
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png

nav:
  - Estrutura do site: index.md
  - O Painel de Planejamento e Orçamento: sobre-painel.md
  - Construção do painel: construcao.md
  - Publicação e atualização: publicacao.md
  - Glossário: glossario.md
  - FAQ: faq.md

extra_css:
  - stylesheets/extra.css